### ISSUE TITLE
📝 Modify `pull_request_template.md`

### ISSUE THREAD

**Issue by canasmh** [canasmh/iron-track-mobile#17]
## What needs updating?

The pull request template.

## Proposed Changes

Currently, the pull request template does not include a check for change log updates in the PR checklist.

## Why is this needed?

This change is necessary because every modification made to the application should be noted in the CHANGELOG

**Comment by Brijeshthummar02** [comment]
@canasmh assign me.

**Comment by canasmh** [comment]
> @canasmh assign me.

@Brijeshthummar02 Thank you for your interest. I would very much appreciate contributions to the project but I am not quite ready for this yet. I want contributing guidelines and expectations documented first before I assign issues to other people. Thank you!

**Comment by Brijeshthummar02** [comment]
yeahh sure!
